# Introduction to Numpy

Numpy is the core library for scientific computing in Python and especially useful for high-dimensional array operations. You will use this library a lot in your data science work, so let's get started!

## 1. Numpy basics
To use Numpy, we first need to import the numpy package:

In [1]:
import numpy as np

### Arrays
Numpy arrays are similar to the array data structures in Java and C: they are fixed-size grids that store homogeneous data, i.e., elements of the same data type. An array of rank $n$ has $n$ dimensions, and its shape is an $n$-element tuple where each element denotes the size of an array along a particular dimension.

A simple way to create Numpy arrays is by calling the `np.array` function on an array-like object, for example a Python list:

In [2]:
a = np.array([[1., 2.], [3., 4.]])
# a is 2x2 matrix
print(a.shape)

# type float is inferred
print(a.dtype)

# element access by a[row_index, col_index]
print(a[0, 1])

(2, 2)
float64
2.0


Numpy also provides many other functions to create arrays:

In [3]:
np.zeros((2,3,4)) # array of zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [4]:
np.ones((3,3)) # array of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.full((2,2), 100) # constant array

array([[100, 100],
       [100, 100]])

In [6]:
np.eye(2) # identity matrix

array([[1., 0.],
       [0., 1.]])

In [7]:
np.random.normal((2, 3)) # random sample from a standard normal distribution

array([2.5369315 , 2.22893802])

#### Caution about array shapes

We should emphasize a very common source of confusion: the shape `(2,)` is **different from** the shape `(2,1)` or `(1,2)`; the former is a 1D array while the latters are 2D. As you will see throughout this notebook, the 1D and 2D arrays behave very differently in many matrix operations, so make sure to check your dimensions carefully!

In [5]:
a = np.array([1,2])
print( a.shape )

b = np.array([[1,2]])
print( b.shape )

c = np.array([[1], [2]])
print( c.shape )

(2,)
(1, 2)
(2, 1)


Note also that the shape `(2,)` for the 1D array from above implies that it has two rows, i.e., it is a **column vector**. Therefore, even when we write `a = np.array([1,2])` in our code, we should always think of it as
$$a = \begin{pmatrix} 1 \\ 2 \end{pmatrix}.$$

As a consequence, transposing a 1D array does not change anything -- it will still be a column vector.

In [6]:
print(a, a.shape)
print(a.T, a.T.shape)

[1 2] (2,)
[1 2] (2,)


### Array indexing
#### Slicing
Similar to Python lists, numpy arrays can be sliced by using `start_index:end_index`. You must specify a slice for each dimension of the array. To take all values in a certain dimension, you can use a standalone `:` or just leave that dimension blank. See example below:

In [8]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
# get elements from row 0 to 2 and from column 1 to 3
print(a[0:2,1:3])

# get elements from row 0 to 2 in all columns
print(a[0:2,:])

# equivalently, can omit the standalone : as well
print(a[0:2,])

[[2 3]
 [6 7]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [9]:
print("The original array \n", a)
b = a[0:2,1:3]
b[0, 0] = 100 # b[0, 0] is in the same place as a[0,1]
print("The slice after modifying \n", b)
print("The original array after modifying \n", a)

The original array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The slice after modifying 
 [[100   3]
 [  6   7]]
The original array after modifying 
 [[  1 100   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


If you want to get only one element from a certain dimension, you can use integer indexing (which can be mixed with slice indexing in other dimensions). Note that doing this will result in an array of lower rank. For example, let's get the element at column 2 from row 0 to 2 in the following array:

In [10]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# using slicing in all dimensions preserves the rank
print(a[0:2, 2:3])

# each dimension with integer indexing reduces the rank by 1
print(a[0:2, 2])

[[3]
 [7]]
[3 7]


#### Integer array indexing
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to quickly combine different portions of an input array to form a new output array. For example, given an input matrix `a`, we can form a new matrix with two copies of row 0 in `a` and three copies of row 1 in `a` as follow: 

In [11]:
a = np.array([[1,2], [3, 4], [5, 6]])
print("The input matrix \n", a)
print("Two copies of row 0, three copies of row 1 \n", a[[0, 0, 1, 1, 1],:])

The input matrix 
 [[1 2]
 [3 4]
 [5 6]]
Two copies of row 0, three copies of row 1 
 [[1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


One useful trick with integer array indexing is selecting or mutating one element from each dimension of an array:

In [3]:
# original array
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

# an array with two elements: a[0,1] and a[3,2]
print(a[[0,3], [1,2]])

# increment a[0,1] and a[3,2] by 100 in one line
a[[0,3], [1,2]] += 100

print("new array \n", a)

[ 2 12]
new array 
 [[  1 102   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11 112]]


#### Boolean array indexing

You can apply a Boolean condition on a Numpy array in the same way you apply it to a single variable. Doing so will apply such condition to every element in the input array, resulting in a new array with the same shape where every element is either `True` or `False`.

In [13]:
import numpy as np

a = np.array([[1,2], [3,4], [5,6]])

# True if a[i, j] > 2 and False otherwise
print(a > 2)

# True if 2 < a[i, j] < 5 and False otherwise
print((a > 2) & (a < 5))

[[False False]
 [ True  True]
 [ True  True]]
[[False False]
 [ True  True]
 [False False]]


A Boolean array can be used as index on an input array `a`, which will return a rank 1 array consisting of the elements in the `a` that correspond to a `True` entry. Note that the return value is always one dimensional, regardless of the rank of `a`.

In [14]:
# a is 4-dimensional array
a = np.random.normal((6,7,8,9))

# Boolean array indexing yields 1-dimensional array
print(a[a > 0.5])

[5.23930845 8.44723556 7.50676281 8.64583154]


### Data types

To optimize operations, Numpy provides a set of supported [data types](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html). If your array elements do not conform to these data types (e.g., you have a Numpy array of dictionaries), the default data type will be `object` (but why would you want a Numpy array of dictionaries??). Numpy will try to guess the data type of an array upon creation, but you can also explicitly specify the data type, for example:

In [15]:
# inferred datatype int
x = np.array([0, 1, 2])

# inferred datatype float
y = np.array([1.5, 2.5])

# specified datatype int
z = np.array([1, 2], dtype=np.int64)

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


You can also convert between datatypes by using `.astype`:

In [16]:
# convert int to float
print(x.astype(np.float64))

# convert float to int, this involves rounding
print(y.astype(np.int64))

# equivalent to Boolean array x != 0
print(x.astype(np.bool))

[0. 1. 2.]
[1 2]
[False  True  True]


### Array math

Basic mathematical functions can be performed elementwise on Numpy arrays. For binary operators, the two input arrays must have the same shape.

In [17]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x**2)
print(np.sqrt(x))

print(x + y)
print(x * y)
print(x / y)

[[ 1  4]
 [ 9 16]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use `np.dot` to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot` is available both as a function in the numpy module and as an instance method of array objects:

In [7]:
v = np.array([1, 3])
w = np.array([5, 7])

# dot product of v and w
print(v.dot(w))

# equivalent function to compute dot product
print(np.dot(v, w))

26
26


Note that because `dot(a, b)` can handle most multiplication operations, how it operates depends on what the inputs are (see the [Numpy documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)). Because of this flexibility, if you don't check our input dimensions carefully, `dot` may perform something unexpected, leading to very subtle bugs. Therefore, in cases where an alternative operator is available:
1. if both `a` and `b` are 2-dimensional arrays, `dot` is equivalent to `matmul` or `@`
2. if either `a` or `b` is scalar, `dot` is equivalent to `*` (elementwise multiplication),

you should use these alternatives instead.

As another note, recall from Section 1 that 1D arrays in Numpy are always treated as column vectors. Therefore, to perform operations that involve both row and column vectors, we cannot use the typical matrix multiplication operators, but instead need to call the appropriate Numpy function. For example, to compute the outer product $w \times w^T$, which we expect to be a $2 \times 2$ matrix, we can use `np.outer`:

In [10]:
# this will work
print(np.outer(w, w))

# this will not work because w and w.T are both column vectors
# so we only get the dot product instead of a 2x2 matrix
print(w @ w.T)

[[25 35]
 [35 49]]
74


Numpy also provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [19]:
x = np.array([[1,2],[3,4]])

# sum along the columns
print(x.sum(axis = 0))

# sum along the rows
print(x.sum(axis = 1))

# sum all elements
print(x.sum())

[4 6]
[3 7]
10


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

The most simple example is to increment each element in a matrix by a constant:

In [21]:
x = np.array([[1,2], [3, 4]])
print(x + 10)

[[11 12]
 [13 14]]


Recall our earlier note that binary elementwise operation can only be carried out when the two input matrices have the same shape. Here `x` is two-dimensional and `10` is zero-dimensional, so why did `x + 10` work out? The reason is that Numpy automatically turns `10` into a constant matrix that matches the shape of `x` (i.e., `[[10, 10], [10, 10]]`). This process is known as **broadcasting**.

We can broadcast not only constants but also a lower-rank matrix when it is used together with a higher-rank matrix, for example:

In [22]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1, 0, 1])
# add v to each row of x using broadcasting
print(x + v)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Naturally, the question is: when does broadcasting **not work**? For example, if `a` is a 4x2 matrix and `b` is a 2x1 matrix, would `a + b` work?

In [23]:
a = np.ones((4,2))
b = np.ones((2,1))
a + b

ValueError: operands could not be broadcast together with shapes (4,2) (2,1) 

As it turns out, this does not work. In general, the rule for broadcasting is as follows.

1. If `a` and `b` have different ranks, add one-element dimensions to `a` or `b` until they have the same ranks. For example, if `a = [[1,2],[3,4]]` (2-dimensional) and `b = 10` (0-dimensional), we would turn `b` to 2-dimensional, i.e., `[[10]]`.

2. Now that `a` and `b` have the same ranks, iterate through each dimension `i` of `a` and `b`:
    * If the shapes of `a` and `b` in dimension `i` are the same, move on.
    * Else if the shape of `b` is 1 in dimension `i`, copy dimensions `[i, i+1, ...]` of `b` until its shape is the same as that of `a`.
    * Else if the shape of `a` is 1 in dimension `i`, copy dimensions `[i, i+1, ...]` of `a` until its shape is the same as that of `b`.
    * Else, raise "ValueError: operands could not be broadcast together"
   
For example, `a = [[1,2],[3,4]]` (2-dimensional) and `b = 10` (0-dimensional), broadcasting involves the following steps:

1. Turn `b` into 2-dimensional, i.e., `b = [[10]]`, so that it has the same rank as `a`.
2. Loop through dimension `i = 0` and `i = 1`:
    * With `i = 0, a = [[1,2],[3,4]], b = [[10]]`, we see `a.shape[i] = 2` and `b.shape[i] = 1`. Therefore, we would copy dimension `i+1` of `b`, which is `[10]`, so that `b.shape[i] = 2`, i.e., `b` has two rows. This would turn `b` into `[[10], [10]]`.
    * With `i = 1, a = [[1,2],[3,4]], b = [[10], [10]]`, we similarly copy dimension `i+1` of `b`, which is the constant 10, to each row, resulting in `b = [[10, 10], [10, 10]]` as expected.

An implication of this rule is that, while we earlier mentioned the typical use case of broadcasting is to operate a "large" matrix with a "small" matrix, this is not necessarily the case. For example, a matrix of shape (2,1) can be added to a matrix of shape (1,2) through broadcasting:

In [24]:
a = np.array([[1], [2]])
a + a.T

array([[2, 3],
       [3, 4]])

We should also note that the matrix manipulations involved in step 1 and 2 of the broadcasting process above can be useful on their own. In particular, adding one-element dimensions to a matrix can be done in array indexing with the use of the keyword `None`, which is equivalent to `np.newaxis` (for more details see the [documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)):

In [2]:
# b is 0D
b = np.array(10)
print(b)

# turn 0D to 1D
b_1d = b[None]
print(b_1d)

# turn 0D to 2D
b_2d = b[None, None]
print(b_2d)

# turn 1D to 2D, note the use of :
print(b_1d[:, None])

10
[10]
[[10]]
[[10]]


For outer products on 1D vectors, other than using `np.outer` as we introduced earlier, it is also possible to broadcast the 1D vectors to 2D matrices and multiply them as usual:

In [11]:
v = np.array([1, 3])
w = np.array([5, 7])

print(np.outer(v, w))

print(v[:,None] @ w[:,None].T)

[[ 5  7]
 [15 21]]
[[ 5  7]
 [15 21]]


And copying dimensions can be done with `np.tile`:

In [26]:
x = np.array([1, 2, 3])
# stack 3 copies of x on top of each other
np.tile(x, (3, 1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](https://numpy.org/doc/stable/reference/index.html) to find out much more about numpy.

In the next section, we will cover how Numpy can be used for efficient computation of complex procedures.

## 2. Applications of Numpy

The primary advantage of Numpy is that, due to its underlying C implementation, array-based operations are much faster than in Python. For example, let's consider the task of summing over all integers from 1 to 10000.

In [27]:
n = 10000
l = np.arange(n)

In [28]:
%%timeit
s = 0
for item in l:
    s += item

2.29 ms ± 197 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [29]:
%%timeit
l.sum()

6.44 µs ± 59.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Noting that $1ms$ = $1000\mu s$, we see that using Numpy's `sum` function is 350+ times faster than normal Python loop, and this difference is even more prominent for larger input size. Therefore, a rule of thumb for computationally heavy tasks is: **use Numpy whenever possible**! Avoid running computations using Python loops, or on Python lists; if you want to perform any operation over a large dataset, always thinks in terms of matrices.

In this section, we will look at how to implement common machine learning procedures using Numpy. The main takeaway is for you to adopt a matrix-based mindset. If you need a linear algebra refresher, take a look at http://www.cs.cmu.edu/~zkolter/course/linalg/. In particular, the three sections about "Putting Equations into Matrix Form" are closely related to our materials.

### Example 1: Log-likelihood function
Given $n$ iid data points $\{x^{(i)}\}_{i=1}^n$ from a distribution with pdf / pmf $P$, we define the log-likelihood of the data given the model $\theta$ as
\begin{equation}
    \boxed{\mathcal{LL}(\theta) = \log p(x^{(1)}, \ldots, x^{(n)}; \theta) = \sum_{i=1}^n \log P(x^{(i)}; \theta).}
\end{equation}

There are two steps to carry out this computation:
1. For each data point $x^{(i)}$, compute $\log P(x^{(i)}; \theta)$.
2. Sum over all the $\log P(x^{(i)}; \theta)$.

The "for each" part in step 1 seems indicative of a loop, but let's think about how we can get all the $\log P(x^{(i)}; \theta)$ **together in one matrix**. Assume the input data is in the matrix form $X \in \mathbb{R}^{n \times d}$. To apply the $\log P(x)$ function to every row $x$ in $X$, we can use `np.apply_along_axis`, which, as the name suggests, applies an input function to every row or column of a matrix. Then we just sum over the return value in every row by `.sum`. Hence, our implementation is as follows.

In [30]:
def log_likelihood(X, log_p, theta):
    # log_p is the log pdf / pmf function of the distribution of X
    # axis = 1 means applying along the rows
    return np.apply_along_axis(lambda x: log_p(x, theta), 1, X).sum()

# example: log likelihood of getting 5 heads from tossing a fair coin 5 times
from scipy.stats import bernoulli
log_likelihood(np.ones((5,1)), bernoulli.logpmf, 1/2) == np.log(1/(2**5))

True

### Example 2: Linear Regression
Given input data $X \in \mathbb{R}^{n \times d}$ and output $Y \in \mathbb{R}^{n \times 1}$, linear regression attempts to model the relationship between $X$ and $Y$ by a linear function $h_\theta(x) = \theta^Tx$, where $\theta \in \mathbb{R}^{d \times 1}$. To evaluate the goodness of fit of a particular parameter $\theta$, we compute the mean squared error
$$\boxed{\mathcal L(\theta) = \frac 1 n \sum_{i=1}^n (\theta^T x^{(i)} - y^{(i)})^2}$$

To implement this loss function, we should not compute the individual $(\theta^T x^{(i)} - y^{(i)})^2$ values and add them up, as this requires a loop. Instead, taking advantage of the fact that $X$ and $Y$ are already in matrix format, we can get all the $\theta^T x^{(i)} - y^{(i)}$ terms **together in one vector**:
$$M = X \theta - Y = [\theta^T x^{(1)} - y^{(1)}, \theta^T x^{(2)} - y^{(2)}, \ldots, \theta^T x^{(n)} - y^{(n)}]^T$$
and then compute the sum of squares of the elements in this matrix simply by `(M**2).sum()` or `np.linalg.norm(M)**2`.

In [14]:
def mse(theta, X, Y):
    return ((X @ theta - Y)**2).sum() / X.shape[0]

# example: MSE of the line y = 2x w.r.t the dataset {(1, 2), (2, 5), (3, 8)} is 5/3
X = np.array([[1], [2], [3]])
Y = np.array([2, 5, 8])
theta = np.array([2])
mse(theta, X, Y)

1.6666666666666667

### Example 3: K-means Clustering

K-means clustering attempts to assign each data point to one of $k$ clusters $C = \{0, 1, \ldots, k-1\}$ so that the total distance between each data point and its nearest cluster center (i.e., the *within-cluster variance*) is minimized. At a high level, the algorithm has three steps, where step 2 and 3 can be repeated until convergence:

1. Initialize the cluster centers $U \in \mathbb{R}^{k \times d}$ randomly.
2. Assign each data point $x^{(i)}$ to the cluster whose center is closest to it,
$$ y^{(i)} = \text{argmin}_{c \in C} \| \mu^{(c)} - x^{(i)} \|_2^2, \ i = 1, \ldots, n.$$
3. Based on this cluster assignment, recompute the cluster centers:

$$\boxed{\mu^{(c)} \leftarrow \text{Mean}(\{ x^{(i)} \mid y^{(i)} = c \}), \ c \in C}$$

Given input data $X \in \mathbb{R}^{n \times d}$ and cluster assignments $Y \in C^{n \times 1}$, how we can recompute the cluster centers through the conditional sum in step 3? Again, try to resist the temptation to use a for-loop with an inner if-statement to check for $y^{(i)} = c$. Instead, we aim to get all the $\mu^{(c)}$'s **together in one matrix**.

Let's think about a simple example with three 1D data points and two clusters (0 and 1):

$$X = \begin{pmatrix} 1 \\ 7 \\ 24 \end{pmatrix}, \quad Y = \begin{pmatrix} 0 \\ 1 \\ 0 \\ \end{pmatrix}.$$

In this case, our expected output, which is the matrix of all the new $\mu^{(c)}$'s, is
$$U = \begin{pmatrix} (x^{(1)} + x^{(3)})/2 \\ x^{(2)} \end{pmatrix} = \begin{pmatrix} 25/2 \\ 7 \end{pmatrix}.$$

Our goal is to multiply $X$ with another matrix $M$ (or multiply $M$ with $X$) that can yield $U$ right away. Note that $X \in \mathbb{R}^{3 \times 1}$ while $U \in \mathbb{R}^{2 \times 1}$, so the only way for this multiplication to work is $M \in \mathbb{R}^{2 \times 3}$ and
$$MX = \begin{pmatrix} ? & ? & ? \\ ? & ? & ? \end{pmatrix} \begin{pmatrix} 1 \\ 7 \\ 24 \end{pmatrix} = U = \begin{pmatrix} 25/2 \\ 7 \end{pmatrix}.$$
It's not too hard to identify one possible $M$ as
$$M = \begin{pmatrix} 1/2 & 0 & 1/2 \\ 0 & 1 & 0 \end{pmatrix}.$$
So how does this $M$ relate to $Y$? Note that $M$ seems to have a 0 in each column, which reminds us of the [one-hot encoding representation](https://www.kaggle.com/dansbecker/using-categorical-data-with-one-hot-encoding). Indeed, the one-hot encoding of $Y$ does have a lot of similarity with $M$:
$$Y' = Y_{\text{one hot}} = \begin{pmatrix} 1 & 0 \\ 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad M^T = \begin{pmatrix} 1/2 & 0 \\ 0 & 1 \\ 1/2 & 0 \end{pmatrix}.$$

But where does the denominator 2 come from? Recall that we are taking the cluster mean, and there are two points in cluster 0, so 2 must be the cluster size. More generally, each entry $Y'_{i,j}$ would be turned into $\frac{Y'_{i,j}}{m_j}$, where $m_j$ is the number of 1s in column $j$, i.e., the count of data points in cluster $j$. In other words, we will normalize each column of $Y'$ to obtain $M^T$.

In summary, here are the two steps to compute the cluster centers $U$:
1. Convert $Y$ into one-hot encoding form and normalize every column.
2. Transpose it and multiply with $X$.

In [32]:
def get_cluster_centers(X, Y, k):
    M_transpose = np.eye(k)[Y,:]
    M_transpose /= np.sum(M_transpose, axis = 0)
    return M_transpose.T @ X

X = np.array([[1], [7], [24]])
Y = [0, 1, 0]
get_cluster_centers(X, Y, 2)

array([[12.5],
       [ 7. ]])

Notice the use of integer array indexing to construct $M^T$ from the $k \times k$ identity matrix. Play around with the above code to make sure you understand what each line of code does!

Don't worry if you are not familiar with the above machine learning concepts, you will learn more about them in 10-601! The skill that you should develop from this tutorial is to efficiently implement any math formula or algorithm by utilizing Numpy. The basic idea is that any time you need to compute a set of vectors, think about getting all of them **together in one matrix** via Numpy matrix operations.

## 3. Sparse matrix

Finally, we briefly introduce a useful data structure for Project 1 called *sparse matrix*. These are matrices which contain mostly zero entries and only a few non-zero entries (e.g., adjacency matrices from real-world graphs). Storing all these zeroes in a standard matrix format can be a huge waste of computation and memory. Scipy provides a [sparse matrix library](https://docs.scipy.org/doc/scipy/reference/sparse.html) that specializes in handling this kind of data. An important advantage of Scipy's sparse matrix is that it consumes a lot less memory while being funtionally similar to standard Numpy matrices.

### 3.1 Creating sparse matrix
The standard way to create a sparse matrix is to simply specify the value, row index and column index of every non-zero entry. For example, in the following matrix
$$A = \begin{pmatrix}
    0 & 0 & 3 & 0 \\
    2 & 0 & 0 & 1 \\
    0 & 1 & 0 & 0 \\
    4 & 0 & 1 & 0 
\end{pmatrix}$$
we can construct three lists `data, row, col` to store the locations and values of the 6 non-zero entries.

In [33]:
import scipy.sparse as sp
data = [2, 4, 1, 3, 1, 1]
row = [1, 3, 2, 0, 3, 1]
col = [0, 0, 1, 2, 2, 3]

m = sp.coo_matrix((data, (row, col)), shape = (4, 4))
# .A converts the sparse matrix to its dense representation (of type np.ndarray)
print(m.A)

[[0 0 3 0]
 [2 0 0 1]
 [0 1 0 0]
 [4 0 1 0]]


Note that while `coo_matrix` can also take a dense matrix and convert it to sparse, in practice it is better to avoid the creation of any dense matrix altogether and construct the three lists `data, row, col` as input to `coo_matrix` instead. Similarly, `.A` is useful for printing the dense representation, but actual matrix operations should be performed on the sparse object.

Depending on whether the target matrix operation requires row or column access, a `coo_matrix` object can be converted to either a `csr_matrix` (**compressed sparse row**) or `csc_matrix` (**compressed sparse column**) object. This conversion is necessary, as `coo_matrix` is slow in row and column access, but the conversion process is very fast so don't hesitate to do it.

In [34]:
# CSR matrix allows for fast row access
m_rows = m.tocsr()
print("row at index 2:")
print(m_rows.getrow(2).A)

# CSC matrix allows for fast column access
m_cols = m.tocsc()
print("column at index 2:")
print(m_cols.getcol(2).A)

row at index 2:
[[0 1 0 0]]
column at index 2:
[[3]
 [0]
 [0]
 [1]]


Note that in the above cases, the returned row and column are both **2D sparse matrices**, not 1D vectors like what Numpy would return. If our expected output is 1D vector, we can convert the sparse row / column to dense format and then flatten it:

In [35]:
print(m_rows.getrow(2).A.ravel())
print(m_cols.getcol(2).A.ravel())

[0 1 0 0]
[3 0 0 1]


Per the Scipy documentation, the pros and cons of CSR / CSC format are as follows:

|  	| Pros 	| Cons 	|  	|
|-----	|-------------------------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------	|---	|
| CSR 	| Efficient arithmetic operations CSR + CSR, CSR * CSR, etc. <br>Efficient row slicing <br>Fast matrix vector products 	| Slow column slicing operations (consider CSC) <br>Changes to the sparsity structure are expensive 	|  	|
| CSC 	| Efficient arithmetic operations CSC + CSC, CSC * CSC, etc. <br>Efficient column slicing <br>Fast matrix vector products (CSR may be faster) 	| Slow row slicing operations (consider CSR) <br>Changes to the sparsity structure are expensive 	|  	|
|  	|  	|  	|  	|

Therefore, after constructing a sparse matrix in `coo_matrix` format, we should think about what kind of operations we need to perform and choose the appropriate conversion.

### 3.2 Operating on sparse matrix

Consult the API for [CSR matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html#scipy.sparse.csr_matrix) and [CSC matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html#scipy.sparse.csc_matrix) for their supported operations. In general, standard mathematical transformations (e.g., `power, sqrt, sum`), as well as matrix operations (`dot, multiply, transpose`) are available.

Consider for example the speedup in matrix-vector multiplication when using the sparse matrix format:

In [36]:
# identity matrix in sparse format
A = sp.eye(1000)

# identity matrix in standard Numpy format
B = np.eye(1000)

# vector to multiply with
x = np.random.randn(1000)

In [37]:
%timeit A.dot(x)
%timeit B.dot(x)

6.12 µs ± 167 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
168 µs ± 4.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


We see a 28x increase in speed, though the speedup will increase with sparsity relative to the dense matrix.

An important point to keep in mind when working with sparse matrix is that, if an operation is supported by both `scipy.sparse` and `numpy`, **always use the scipy.sparse version**. Sometimes the `numpy` version will convert the sparse matrix input to dense matrix, which makes our sparse representation pointless. For example, if we use `np.dot(A, x)` instead of `A.dot(x)`, the time taken suddenly increases by a factor of 4500 (because of the sparse to dense conversion time).

In [38]:
%timeit np.dot(A, x)

27.2 ms ± 378 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


![Escalation meme](https://i.kym-cdn.com/photos/images/newsfeed/000/353/279/e31.jpg)